export type ProductProps = {
    productId: number,
    brand: string,
    model: string,
    year: number,
    mileage: number,
    displacement: number,
    engineType: string,
    transmission: string,
    drivetrain: string,
    bodyType: string,
    color: string,
    steeringWheel: string,
    price: number,
    images: string[],
    description: string,
    popular: boolean,
    raiting: number,
}